language: node_js
node_js:
  - 0.10
notifications:
  email:
    on_success: change
    on_failure: always
script: >
  node_modules/.bin/mocha --reporter spec
                          --compilers coffee:coffee-script/register
                          --require postmortem/register
                          .test
cache:
  directories:
  - node_modules
