module.exports =
  coffee:   require './coffee'
  css:      require './css'
  html:     require './html'
  jade:     require './jade'
  js:       require './js'
  json:     require './json'
  map:      require './map'
  markdown: require './markdown'
  md:       require './markdown'
  mkd:      require './markdown'
